Repository ciselab/TestGenie, pull requests merged in 2022-06, with the labels that each got.

#143 Save telemetry data to file
  .gitignore
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/listener/TestGenieTelemetrySubmitListenerImpl.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestGenieTelemetryService.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginComponent.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/TestGenieSettingsState.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/defaults/TestGenie.properties
Labels: type: enhancement

#133 Caching
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsActionLine.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsActionMethod.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsUtils.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/ResultWatcher.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Runner.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/TestGenerationResultListener.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/listener/TestGenerationResultListenerImpl.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseCachingService.kt
  src/main/resources/META-INF/plugin.xml
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseCachingServiceTest.kt
Labels: type: improvement

#152 Fix caching service returning same test multiple times
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseCachingService.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseCachingServiceTest.kt
Labels: type: bug

#149 Remove tests from cache
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Runner.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseCachingService.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/TestGenieSettingsState.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseCachingServiceTest.kt
Labels: type: enhancement

#156 Telemetry Path Bugfix
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginComponent.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/TestGenieSettingsState.kt
  src/main/resources/defaults/TestGenie.properties
Labels: type: bug

#166 Applying tests removes "test" and "coverage" tabs and hides tool window
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/CoverageVisualisationService.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
Labels: type: improvement

#165 Implement cache removal
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseCachingService.kt
Labels: type: improvement

#169 Button to actually run evosuite when showing cached tests
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/editor/Workspace.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Runner.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/listener/TestGenerationResultListenerImpl.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
Labels: type: improvement

#179 Delete boilerplate test code
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/MyPluginTest.kt
  src/test/testData/rename/foo.xml
  src/test/testData/rename/foo_after.xml
Labels: type: enhancement

#178 UI testing for test generation tab in tool window - 131
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/GeneratedTestsToolWindowTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/IdeaFrame.kt
  src/test/resources/project/untitled/src/main/java/ArrayUtils.java
Labels: type: testing

#193 Rename "Not killed mutants" to "Survived mutants"
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/coverage/CoverageRenderer.kt
Labels: type: improvement

#194 Show title above each displayed test case
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
Labels: type: improvement

#202 Show the number of selected test cases in tool window
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
  src/main/resources/defaults/Labels.properties
Labels: type: enhancement

#203 Make loading statements funny
  src/main/resources/messages/TestGenie.properties
Labels: type: improvement

#206 Add confirmation popup for removing tests
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/toolwindow/QuickAccessParameters.kt
  src/main/resources/messages/TestGenie.properties
Labels: type: improvement

#205 Coverage visualisation fixes
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/coverage/CoverageRenderer.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/CoverageVisualisationService.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
Labels: type: bug

#207 Change hard coded default values in the labels in quick access parameters
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/toolwindow/QuickAccessParameters.kt
Labels: type: improvement

#209 Fix failing UI tests
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/toolwindow/QuickAccessParameters.kt
  src/main/resources/defaults/Labels.properties
  src/main/resources/messages/TestGenie.properties
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/PsiSelectionTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/IdeaFrame.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/WelcomeFrame.kt
Labels: type: bug

#210 Add a disclaimer and update the documentation
  CONTRIBUTING.md
  README.md
  readme-images/pngs/jacoco.png
  readme-images/pngs/jacocoTable.png
  readme-images/pngs/selectAll.png
  readme-images/pngs/validate.png
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/ProjectBuilder.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/validation/TestCaseEditor.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/validation/ValidationToolWindowFactory.kt
Labels: type: improvement

#212 Improve dynamic validation
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/editor/Workspace.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Pipeline.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/validation/TestCaseEditor.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/validation/Validator.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/listener/TestGenerationResultListenerImpl.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseCachingService.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseCachingServicePropertyBasedTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseCachingServiceTest.kt
Labels: type: improvement
