Repository ciselab/TestGenie, pull requests merged in 2022-05, with the labels that each got.

#17 Basic plugin config
  gradle.properties
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/actions/GenerateTestsForClassAction.kt
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/settings/TestGenieSettingsComponent.form
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/settings/TestGenieSettingsComponent.kt
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/settings/TestGenieSettingsConfigurable.kt
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/settings/TestGenieSettingsService.kt
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/settings/TestGenieSettingsState.kt
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/toolwindow/TestGenieToolWindow.form
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/toolwindow/TestGenieToolWindow.kt
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/toolwindow/TestGenieToolWindowFactory.kt
  src/main/resources/META-INF/plugin.xml
Labels: priority: must-have

#27 Sidebar Tool Window for Quick Access to frequently used parameters - Issue 24
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/toolwindow/TestGenieToolWindow.form
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/toolwindow/TestGenieToolWindow.kt
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/toolwindow/TestGenieToolWindowFactory.kt
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/toolwindow/TestGenieToolWindowService.kt
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/toolwindow/TestGenieToolWindowState.kt
  src/main/resources/META-INF/plugin.xml
Labels: priority: must-have

#26 Create a menu for test case selection
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/actions/GenerateTestsForClassAction.kt
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/services/TestCaseDisplayService.kt
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/toolwindow/TestGenieToolWindow.kt
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/toolwindow/TestGenieToolWindowFactory.kt
  src/main/resources/META-INF/plugin.xml
Labels: type: enhancement, priority: must-have

#28 Settings menu
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/settings/TestGenieSettingsComponent.form
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/settings/TestGenieSettingsComponent.kt
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/settings/TestGenieSettingsConfigurable.kt
  src/main/kotlin/com/github/mitchellolsthoorn/testgenie/settings/TestGenieSettingsState.kt
  src/main/resources/META-INF/plugin.xml
Labels: type: enhancement, priority: must-have

#54 Fix method and class tests generation
  build.gradle.kts
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsActionClass.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsActionMethod.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/actions/GenerateTestsUtils.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Runner.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/SettingsArguments.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/helpers/MethodDescriptorHelper.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/helpers/MethodDescriptorHelperTest.kt
Labels: type: improvement

#59 Add issue number to pull request template
  .github/pull_request_template.md
Labels: type: improvement

#60 Add UI tests
  .github/workflows/run-ui-tests.yml
  build.gradle.kts
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/IdeaFrame.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/SettingsFrame.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/WelcomeFrame.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/utils/RemoteRobotExtension.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/utils/StepsLogger.kt
  src/test/resources/project/untitled/untitled.iml
Labels: type: research

#77 Apply tests to test class
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
Labels: type: enhancement

#83 Fix syntax errors being shown in tool window
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
Labels: type: bug

#82 Allow test cases to be edited in the tool window
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
Labels: type: improvement

#85 Option to provide a custom java binary path
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Runner.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginComponent.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/TestGenieSettingsState.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/defaults/TestGenie.properties
  src/main/resources/messages/TestGenie.properties
Labels: type: improvement

#89 Tests For Quick Access Parameters
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/toolwindow/QuickAccessParametersStateTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/QuickAccessParametersTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/customfixtures/CustomFixtures.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/IdeaFrame.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/QuickAccessParametersFixtures.kt
Labels: type: testing

#92 Coverage test
  build.gradle.kts
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/CoverageVisualisationService.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/CoverageVisualisationServiceTest.kt
Labels: type: testing

#95 Finish Quick Access Testing
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/toolwindow/QuickAccessParameters.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/QuickAccessParametersTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/QuickAccessParametersFixtures.kt
Labels: type: testing

#111 Rename apply button
  README.md
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
Labels: type: improvement

#115 Fix UI tests for macOS
  build.gradle.kts
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/QuickAccessParametersTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/IdeaFrame.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/SettingsFrame.kt
Labels: type: bug

#113 UI testing for coverage visualisation
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginComponent.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/CoverageVisualisationServiceTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsEvoSuiteConfigurableTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurableTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/CoverageVisualisationToolWindowTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/SettingsComponentTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/IdeaFrame.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/SettingsFrame.kt
  src/test/resources/project/untitled/pom.xml
  src/test/resources/project/untitled/src/main/java/ArrayUtils.java
  src/test/resources/project/untitled/target/classes/ArrayUtils.class
  src/test/resources/project/untitled/untitled.iml
Labels: type: testing

#119 Build before running EvoSuite
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/editor/Workspace.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Runner.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginComponent.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/TestGenieSettingsState.kt
  src/main/resources/defaults/TestGenie.properties
  src/main/resources/messages/TestGenie.properties
Labels: type: improvement

#123 Show diff between original and modified test case
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
Labels: type: improvement

#124 Weaken highlighter priority
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/CoverageVisualisationService.kt
Labels: type: improvement

#126 Telemetry data collection
  README_developers.md
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestCaseDisplayService.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/services/TestGenieTelemetryService.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginComponent.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/SettingsPluginConfigurable.kt
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/settings/TestGenieSettingsState.kt
  src/main/resources/META-INF/plugin.xml
  src/main/resources/defaults/TestGenie.properties
Labels: type: improvement

#128 Finish UI tests for Quick Access Parameters and moved checkbox
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/QuickAccessParametersTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/QuickAccessParametersFixtures.kt
Labels: type: testing

#120 Testing PSI selection
  .gitignore
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/PsiSelectionTest.kt
  src/test/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/uiTest/pages/IdeaFrame.kt
  src/test/resources/pizzeria/src/PizzaClasse.java
  src/test/resources/project/pizzeria/pom.xml
  src/test/resources/project/pizzeria/src/main/java/PizzaClasse.java
Labels: type: testing

#136 update thunderdome version
  build.gradle.kts
  src/main/kotlin/nl/tudelft/ewi/se/ciselab/testgenie/evosuite/Runner.kt
Labels: thunderdome
